### PR TITLE
backend stuff professor grade project

### PR DESCRIPTION
**Pull request by obi-el**
added the backend stuff for professor grading a deliverable; what do you guys think

### CODE REVIEW

**Comment by yashp13** [comment]
How are the grades connected to each project? Because I don't see any relation between the Deliverable and Project classes.

**Comment by obi-el** [comment]
deliverables have grades. and each project should keep track of it's  deliverables.

**Comment by yashp13** [comment]
Yes, but how is project doing that? Maybe projects can have a list of deliverables and that way, the grades are directly associated with each project?

**Comment by obi-el** [comment]
yeah, I assumed that's the direction we were moving in.

**Pull request closed without merging**
